### ISSUE TITLE
How goalfred works in AlfredSwiftLibrary?

### ISSUE THREAD

**Issue by iT-Boyer** [raguay/goAlfred#7]
I'm using swift to develop Alfred. I'm surprised to find your blog.
[alfred-workflows-in-swift--cms](https://computers.tutsplus.com/tutorials/alfred-workflows-in-swift--cms-21807)
Referring to your code, I am compatible with swift5 and support SPM management dependency.
[AlfredSwift](https://github.com/iT-Boyer/AlfredSwift)

but
>This is a port of my Alfred go language library that I use in the tutorial Track Project Time With Alfred Timekeeper to Swift. I

I didn't understand the interaction mechanism between swift and Alfred. I installed `go` and installed the `goalfred` library, but it didn't work when I installed it to Alfred.
```sh
[17:34:40.049] 知乎热榜[Script Filter] Ooops! Can't create directory: Error Domain=NSCocoaErrorDomain Code=512 "The file “” couldn’t be saved." UserInfo={NSFilePath=}
Ooops! Can't create directory: Error Domain=NSCocoaErrorDomain Code=512 "The file “” couldn’t be saved." UserInfo={NSFilePath=}
<items><item uidid='' valid='' autocomplete='' type=''><arg></arg><title>如何看待郑爽涉嫌阴阳合同、天价片酬、偷逃税被调查？可能会带来哪些影响？</title><sub>如何看待郑爽涉嫌阴阳合同、天价片酬、偷逃税被调查？可能会带来哪些影响？</sub><icon></icon></item><item uidid='' valid='' autocomplete='' type=''><arg></arg><title>中国首个空间站天和核心舱 4 月 29 日发射成功，对中国航天有哪些重要意义？</title><sub>中国首个空间站天和核心舱 4 月 29 日发射成功，对中国航天有哪些重要意义？</sub><icon></icon></item><item uidid='' valid='' autocomplete='' type=''><arg></arg>
```

**Comment by raguay** [comment]
Hi,

Both of those projects haven't been used in years. I haven't had the time
to maintain them and I quite using the workflows that I created them for.
So, your pretty much on your own. Sorry.

**Comment by iT-Boyer** [comment]
thanks
